name: 'DefectDojo import scan'
description: 'django-DefectDojo import a scan report into an engagement or product.'
inputs:
  destination_url:
    description: 'The defectDojo url'
    required: true
  api_v2_key: 
    description: 'The API v2 key'
    required: true
  test_title:
    description: 'The test title'
    required: true
  tags:
    description: 'tags for the report'
    required: true
  product_name:
    description: 'product name'
    required: true
  engagement:
    description: 'engagement id'
    required: true
  scan_type:
    description: 'scan type. like Snyk Scan, SARIF'
    required: true
  file:
    description: 'import the file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination-url }}
    - ${{ inputs.api-v2-key }}
    - ${{ inputs.test-title }}
    - ${{ inputs.tags }}
    - ${{ inputs.product-name }}
    - ${{ inputs.engagement }}
    - ${{ inputs.scan-type }}
    - ${{ inputs.file }}
branding:
  icon: 'git-commit'
  color: 'green'